### ISSUE TITLE
Controller annotation support

### ISSUE THREAD

**Issue by koruro** [flamewow/nestjs-asyncapi#25]
It seems that the @AsyncApiService decorator only works when placed in a Nestjs provider and is not currently supported by controllers.

**Describe the solution you'd like**
Add a decorator like @AsyncApiController that allow the controllers to generate the async-api docs

**Comment by e-sam** [comment]
I would really like to see the `@AsyncApiService` decorator work with controllers as well. In the [microservice examples](https://docs.nestjs.com/microservices/basics#request-response), in the official docs, all the handlers are placed within controllers. From my point of view, this makes sense, because, depending on your use case, you might have to do input validation and/or input transformation of the event/message payload, before executing the business logic.

I was able to track down the reason of `@AsyncApiService` not working in controllers, to the fact, that `module.components` does not include controllers, but only modules and providers. Unfortunately, I am relatively new to nest, therefore I have no idea, how to include controllers into the list, that the explorer iterates over, to find the decorators metadata.
