### ISSUE TITLE
It doesn't work with typescript v4.8.3

### ISSUE THREAD

**Issue by iamdenny** [flamewow/nestjs-asyncapi#355]
**Describe the bug**
In typescript v4.8.3, it has an error.

**To Reproduce**
1. git clone https://github.com/flamewow/nestjs-asyncapi/
2. npm install
3. npm install typescript@^4.8.3 --save
4. npm start

**Expected behavior**
http://0.0.0.0:4001/async-api should be working

**Screenshots**
<img width="2264" alt="image" src="https://user-images.githubusercontent.com/1505166/191879448-829d2e5a-fa3d-4f51-ab79-8523b1b7707e.png">

**Environment**

Nest version: 0.3.2

Check whether this is still an issue in the most recent Nest version
 
For Tooling issues:
- Node version: v16.13.1
- Platform:  Mac

Others:
- Anything else relevant?  Operating system version, IDE, package manager, ...

**Additional context**

**Comment by iamdenny** [comment]
it doesn't work from typescript v4.7.x ~ v4.8.x

it works with typescript v4.6.4

**Comment by nakamuloud** [comment]
vote +1

**Comment by flamewow** [comment]
@iamdenny do you have that issue only when trying to start manual e2e? Any issues using the library in other projects?

if that's only about the manual e2e of the nestjs-asyncapi - I'm aware of that issue, it's caused by @asyncapi/generator dependency that is not working with the latest TS version, https://github.com/asyncapi/generator/blob/master/package.json#L76

**Comment by iamdenny** [comment]
okay. I found it where is the real issue point. It's not about nestjs-asyncapi module.

Because of @asyncapi/generator as you told above.

I'll make new issue in @asyncapi/generator.

Thanks @flamewow.

**Comment by flamewow** [comment]
https://github.com/asyncapi/generator/issues/841
